### ISSUE TITLE
instanceof used to check interfaces

### ISSUE THREAD

**Issue by 80prozent** [awaytools/as3-to-ts#6]
the issue round this is using Interfaces in instanceof definitions. instanceof is a javascript keyword that compares the structures of two objects, so you can't use it on an interface object as these are not compiled to javascript. It should work with all other objects tho

**Comment by djtuBIG-MaliceX** [comment]
Relevant stackoverflow article discussing this issue with TS: http://stackoverflow.com/questions/14425568/interface-type-check-with-typescript

The updated answer (since Feb 2017) is effectiely saying for every interface, some boilerplate function will also need to be generated to take in any object and comparing all members exist (defined in that return statement).

**Comment by 80prozent** [comment]
ye. we are using a fix in that we provide  helper functions for each interface in order to do the checks

**Comment by ajsantander** [comment]
This issue was moved to ajsantander/sunflower-ts#62
